### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by heyCarlH** [benknoble/Comp410-JUnit#25]
Hi, so I am getting concurrent modification exception for the three integration tests. It all happen to delNode operation. What could cause that? Thanks.

**Comment by benknoble** [comment]
Concurrent modification means a collection is being modified while an iterator is being consumed (like in a for each loop, or a call to an iterator method). It shouldn't be happening in the test code (i.e., I can't find a spot where it could happen). Is the error message suggesting a line in your code?

**Comment by benknoble** [comment]
Can I get the full error messages?

**Comment by heyCarlH** [comment]
Yes. It suggests that my delEdge line in the delNode method (basically I called delEdge method in the delNode method when I need to remove the in edge and out edge of the deleted node). I have hasMap for in edge and out edge in my node class.

`java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at A6_Dijkstra.DiGraph.delNode(DiGraph.java:86)
	at A6_Dijkstra.DiGraphTests.integration3(DiGraphTests.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

`

**Comment by benknoble** [comment]
I'm not getting this behavior with my tests, so I suspect it's internal to your graph class. Whatever line 86 of `delNode` is, it's modifying a HashMap while the HashMap is being iterated over. This is disallowed because changing the state of an iterated collection while iterating it could break the iterator state.

**Comment by heyCarlH** [comment]
Oh, I see. Yeah that is probably the reason. But why didn't I get this kind of error in assignment 5. Is there a way to modify the hash map when iterating over it?

**Comment by benknoble** [comment]
No, there isn't, though I'm not sure why you need to iterate over and modify the HashMap at the same time... I'm not sure why this didn't come up in A5 unless somehow your shortestpath code is affecting it

**Comment by heyCarlH** [comment]
OK. I'm gonna try to deal with it. Thanks.
